### ISSUE TITLE
JSON wrangling stream!

### ISSUE THREAD

**Issue by tanho63** [tanho63/office_hours#1]
If you have an example of JSON you'd like me to look at while we're on-stream, please add it as a comment here!

**Comment by matthewbrandt** [comment]
Here is a recipe database, the instructions and stuff is in JSON (or similar?) and I really had a hard time working with it in SQL.
https://www.kaggle.com/shuyangli94/food-com-recipes-and-user-interactions?select=RAW_recipes.csv

**Comment by tanho63** [comment]
@matthewbrandt I did get a look at this! It's not quite JSON - looks like it's meant to be python pickles.

**Comment by tanho63** [comment]
Closing issue here - had a great stream! VOD here: https://www.twitch.tv/videos/1106257479

Please open new issues if you want to suggest stream content 🤠
