### ISSUE TITLE
error 1 : Input is not proper UTF-8

### ISSUE THREAD

**Issue by ShubhamOulkar** [tanho63/office_hours#2]
_**"i" iterator stops at 2021.**_ 

**How to set Input data encoding in R?**

![image](https://user-images.githubusercontent.com/91728992/157863077-8ac234b4-ddcb-420f-898e-6001cadf932a.png)

library(rvest)
library(tidyverse)
url <- "https://www.tfrrs.org/results_search.html"
data = c()
page = c() 
for (i in 2009:2022){
  page <- httr::POST(url = url,
                     body = list(
                             meet_name = "",
                             sport = "track:xc",
                             state = "",
                             month = "",
                             year = as.character(i))
                     ) %>%
          httr::content() %>% 
          html_element("table") 
  
  tables <- html_table(page) %>% 
    cbind(tibble(url  = page %>% 
                   html_elements("a") %>%
                   html_attr("href")
                 )
          )
  
  data = rbind(tables,data)
}

**Comment by tanho63** [comment]
Hi! This probably isn’t the right venue to ask, you should probably bring it up in something like R4DS Slack (https://r4ds.io/join)
